name: dbutils
description: Database utilities class library for SQLite and any number of other DBMS implemented in the future.

version: 3.3.0

homepage: https://github.com/AndriousSolutions/dbutils
repository: https://github.com/AndriousSolutions/dbutils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^2.0.0

  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^1.0.0

  # Web only.
  # https://pub.dev/packages/firebase_core
  firebase_core: ^1.0.0

  # RealTime Database
  # https://pub.dev/packages/firebase_database
  firebase_database: ^7.0.0

  # https://pub.dartlang.org/packages/path_provider
  path_provider: ^2.0.0

  # https://pub.dev/packages/path
  path: ^1.0.0

  # https://pub.dartlang.org/packages/sqflite#-changelog-tab-
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

##   http://127.0.0.1:61711/C:/Programs/Tools/Projects/Flutter/packages/dbutils?authToken=iJUvzi1HXT0%3D